apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: webapp-sandbox
namePrefix: sandbox-
resources:
  - ../../base
configMapGenerator:
  - name: web-content
    behavior: replace
    files:
      - index.html
